networks:
  vo_erp:

services:

  # Web Server Service
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    depends_on:
      - app
    networks:
      - vo_erp

  # Application Service
  app:
    container_name: vo_erp
    build: 
      # context: ./php
      dockerfile: Dockerfile
    volumes:
      - .:/var/www
    ports:
      - "9000:9000"
    working_dir: /var/www
    networks:
      - vo_erp
